mimic/app/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.views.generic import TemplateView

# from mimic.app.views.views import AlphaDetailView
# from mimic.app.views.views import BetaDetailView
# from mimic.app.views.views import DimerDetailView
# from mimic.app.views.views import DimerListView
# from mimic.app.views.views import DrugDetailView
# from mimic.app.views.views import PdbListView
# from mimic.app.views.views import PdbDetailView
# from mimic.app.views.views import DrugListView
# from mimic.app.views.views import ProteinInteractorDetailView
# from mimic.app.views.views import ProteinInteractorListView
from .views import browser, downloads, help, home, interactions, search, structures, views

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('home'), permanent=True), name='app', ),
    path('home', home.HomePageView, name='home', ),
    path('interactions/<slug:protein>', interactions.InteractionsView.as_view(), name='interactions', ),
    path('browser', browser.BrowserView.as_view(), name='browser', ),
    path('search', search.SearchView.as_view(), name='search', ),
    path('downloads', downloads.DownloadView, name='downloads', ),
    path('help', help.HelpView, name='help', ),
    path('integrins/', views.DimerListView.as_view(), name='integrins'),
    path('alpha/<slug:name>', views.AlphaDetailView.as_view(), name='alpha'),
    path('beta/<slug:name>', views.BetaDetailView.as_view(), name='beta'),
    path('dimer/<slug:lookup_name>', views.DimerDetailView.as_view(), name='dimer'),
    path('about', TemplateView.as_view(template_name="app/about.html"), name='about'),
    # path('pdbs/', views.PdbListView.as_view(), name='pdbs'),
    path('pdbs/', structures.StructureView, name='pdbs'),
    path('pdb/<slug:pdb>', views.PdbDetailView.as_view(), name='pdb'),
    path('drugs/', views.DrugListView.as_view(), name='drugs'),
    path('drug/<slug:name>', views.DrugDetailView.as_view(), name='drug'),
    path('protein-interactors/', views.ProteinInteractorListView.as_view(), name='protein-interactors'),
]

mimic/mimic/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.urls import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path( r'',RedirectView.as_view(url=reverse_lazy('home'), permanent=True),),
    path('admin/', admin.site.urls),
    path(r'app/', include('app.urls')),
]

mimic/app/models.py
from IntegrinDiagram.integrinDiagram import build_dimer_diagram
from IntegrinDiagram.integrinDiagram import build_dimer_thumbnail
from IntegrinDiagram.integrinDiagram import build_pdb_diagram
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse


# This handler forces all Model and Model fields to be validated before saving.
# See for more info:
# https://docs.djangoproject.com/en/2.0/ref/models/instances/#validating-objects
@receiver(pre_save)
def pre_save_handler(sender, instance, *args, **kwargs):
    instance.full_clean()


class Monomer(models.Model):
    """ A Monomer is a single Alpha or Beta Integrin subunit. The Monomer model
    houses all information which is specific to an Integrin monomer.

    Attributes:
        name (str): A name for the Monomer. e.g.: 'alpha-X'
        uniprot (str): The 6 character Uniprot ID for the subunit
        ensg (str): The 15 character Ensemble Gene ID for the gene
                    corresponding to each monomer
        gene_name (str): A human-friendly gene name
        subunit (str): Subunit type, one of: 'alpha' or 'beta'
        length (int): Length of the Monomner's protein sequence (number of
                      amino acids)
        alpha_interaction_domain (bool, optional): Whether this is an Alpha
                                                   subunit which acts as sole interaction domain. True or
                                                   False for Alpha subunits,
                                                   None for Beta subunits
        sequence (str): The amino acid sequence
        expression (str, optional): A string with expression information from
                                    the Human Protein Atlas
        structure (obj:`MonomerToStructure`): A ManyToMany ForeignKey to the
                                              Structures model, via
                                              intermediary model
                                              MonomerToStructure
        notes (str, optional): Extra information stored as notes

    """

    SUBUNITS = (
        ('alpha', 'alpha'),
        ('beta', 'beta'),
    )

    TAXA = (
        ('Metazoa', 'Metazoa'),
        ('Chordata', 'Chordata'),
    )

    name = models.CharField(max_length=30, unique=True)
    protein = models.OneToOneField(
        "Protein",
        on_delete=models.CASCADE,
    )
    ensg = models.CharField(max_length=15, unique=True)
    gene_name = models.CharField(max_length=30, unique=True)
    subunit = models.CharField(max_length=5, choices=SUBUNITS)
    alpha_interaction_domain = models.NullBooleanField(null=True)
    length = models.IntegerField()
    sequence = models.TextField()
    expression = models.TextField(null=True)
    structure = models.ManyToManyField(
        "Structure",
        through="MonomerToStructure",
    )
    notes = models.TextField(null=True, blank=True)

    def display_name(self):
        """ Return a nicely formatted name as: <alpha.name>/<beta.name>
        """
        if self.subunit == 'alpha':
            return self.name.replace('alpha', 'α').replace('-', '')
        elif self.subunit == 'beta':
            return self.name.replace('beta', 'β').replace('-', '')
        else:
            raise (
                "Invalid subunit value '{0}'. Refusing to continue".format(
                    self.subunit,
                )
            )

    def uniprot_link(self):
        """ Returns a link to the Uniprot entry for this Monomer via the
        Protein model.
        """
        return self.protein.uniprot_link()

    def ensembl_link(self):
        """ Returns a link to the Ensembl entry for this Monomer.
        """
        return "https://www.ensembl.org/id/{0}".format(self.ensg)

    def __str__(self):
        return self.display_name()


class Dimer(models.Model):
    """ A Dimer is a full Integrin complex consisting of a single Alpha and a
    single Beta subunit.

    Attributes:
        name (str): A name for the Dimer. Automatically generated from
            Alpha and Beta subunit names as: <alpha.name>/<beta.name>
        alpha (obj:`Monomer`): ForeignKey to the Monomer model, specifying
                               Alpha subunit
        beta (obj:`Monomer`): ForeignKey to the Monomer model, specifying
                              Beta subunit
        expression (str, optional): A string with expression information from
                                    the Human Protein Atlas
        function (str, optional): Extra information stored as notes
    """

    lookup_name = models.CharField(
        max_length=30,
        unique=True,
        editable=False,
    )
    alpha = models.ForeignKey(
        "Monomer",
        on_delete=models.CASCADE,
        related_name='alpha'
    )
    beta = models.ForeignKey(
        "Monomer",
        on_delete=models.CASCADE,
        related_name='beta'
    )
   
    expression = models.TextField(null=True)

    function = models.TextField(null=True)
    
    

    def display_name(self):
        """ Return a nicely formatted name as: <alpha.name>/<beta.name> (with
        greek caracters)
        """
        return u"{0}/{1}".format(
            self.alpha.name.replace('alpha', 'α').replace('-', ''),
            self.beta.name.replace('beta', 'β').replace('-', ''),
        )

    def save(self, *args, **kwargs):
        """ Custom save to populate the "name" field.
        """
        self.lookup_name = "{0}_{1}".format(self.alpha.name, self.beta.name)
        super(Dimer, self).save(*args, **kwargs)

    def __str__(self):
        return self.display_name()

    class Meta:
        unique_together = (("alpha", "beta"))

    def generate_dimer_diagram(self):
        """ Generates a diagram from the IntegrinDiagram Module
        """
        return build_dimer_diagram(self)

    def generate_dimer_thumbnail(self, filepath):
        """ Generates a png thumbnail from the IntegrinDiagram Module
        """

        build_dimer_thumbnail(self, filepath)

    def get_absolute_url(self):
        return reverse("dimer", args=[self.lookup_name])


class AlternativeName(models.Model):
    """ Alternative Protein names for Monomers.

    Attributes:
        monomer (obj`Monomer`): ForeignKey to the Monomer model
        name (str): An alternative name for the Monomer
    """

    protein = models.ForeignKey(
        "Protein",
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = (("protein", "name"))


class MonomerToStructure(models.Model):
    """ The ManyToMany intermediary model linking Monomers to Structures.

    Attributes:
        monomer (obj`Monomer`): ForeignKey to the Monomer model
        structure (obj`Structure`): ForeignKey to the Structure model
        start (int): start position (amino acid number) of structure, 1 based
        stop (int): stop (last) position (amino acid number) of structure, 1
                    based

    """

    monomer = models.ForeignKey("Monomer", on_delete=models.CASCADE)
    structure = models.ForeignKey("Structure", on_delete=models.CASCADE)
    start = models.IntegerField()
    stop = models.IntegerField()

    def __str__(self):
        return "M2M: {0} / {1}".format(self.monomer, self.structure)

    class Meta:
        unique_together = (("monomer", "structure"))


class Pdb(models.Model):
    """ Protein Database (PDB) information.

    Attributes:
        pdb (str): The 4 character PDB ID
        exp_tech (str):  Experimental technique used
        resolution (float, optional): Resultion
        alpha (obj:`Monomer`): ForeignKey to Monomers model
        beta (obj:`Monomer`): ForeignKey to Monomers model
        alpha_domain (obj:`ManyToMany.Structure`, optional): ManyToMany
            ForeignKey to Structure model.
        beta_domain (obj:`ManyToMany.Structure`, optional): ManyToMany
            ForeignKey to Structure model.
        alpha_chain (str): Series of letters representing PDB Chains.
        beta_chain (str): Series of letters representing PDB Chains.
        protein (obj:`PdbToProtein`, optional): ManyToMany ForeignKey via
            PdbToProtein models
        other_interactors (str, optional): Other interactors.

    See the PdbParser for more information on Parsing these values.
    """

    EXP_TECHS = (
        ('NMR', 'NMR'),
        ('X-ray', 'X-ray'),
        ('Electron microscopy', 'Electron microscopy'),
        ('Model', 'Model'),
    )

    pdb = models.CharField(
        max_length=4,
        unique=True,
        verbose_name='PDB ID',
    )
    exp_tech = models.CharField(
        max_length=20,
        choices=EXP_TECHS,
        verbose_name="Experimental technique",
    )
    resolution = models.FloatField(blank=True, null=True)
    alpha = models.ForeignKey(
        Monomer,
        on_delete=models.CASCADE,
        related_name='pdb_alpha',
        blank=True,
        null=True
    )
    beta = models.ForeignKey(
        Monomer,
        on_delete=models.CASCADE,
        related_name='pdb_beta',
        blank=True,
        null=True
    )
    alpha_domain = models.ManyToManyField(
        'Structure',
        related_name='pdb_alpha_domain',
    )
    beta_domain = models.ManyToManyField(
        'Structure',
        related_name='pdb_beta_domain',
    )
    alpha_chain = models.CharField(max_length=62, blank=True, null=True)
    beta_chain = models.CharField(max_length=62, blank=True, null=True)
    protein = models.ManyToManyField(
        'Protein',
        through="PdbToProtein",
    )

mimic/app/views/about.py
from django.shortcuts import render
from app.models import ProteinInteractor
import pprint


def AboutView(request):

    data = ProteinInteractor.objects.values_list('protein', 'protein__uniprot', 'name', 'organism',
                                                 'type_of_interaction').distinct()
    context={'records':list()}

    for row in data:
        adat = {"protein": row[1]}
        adat["name"] = row[2]
        adat["organism"] = row[3]
        adat["type_of_interaction"] = row[4]
        expmethod = ProteinInteractor.objects.filter(protein=row[0]).values_list(
            "experimental_method").distinct().order_by("experimental_method")
        adat["experimental_method"] = ', '.join(str(item[0]) for item in expmethod)
        integrins = ProteinInteractor.objects.filter(protein=row[0]).values_list(
            "target_integrin").distinct().order_by("target_integrin")
        adat["integrins"] = ', '.join(str(item[0]) for item in integrins)
        # print(adat)
        context['records'].append(adat)

    return render(request, 'app/browser.html', context)

mimic/app/views/downloads.py
from app.models import ProteinInteractor
from django.shortcuts import render


def DownloadView(request):
    data = ProteinInteractor.objects.all()

    context = {"records": data}

    return render(request, 'app/downloads.html', context)

mimic/app/views/help.py
from django.shortcuts import render
from app.models import ProteinInteractor
import pprint


def HelpView(request):

    data = ProteinInteractor.objects.values_list('protein', 'protein__uniprot', 'name', 'organism',
                                                 'type_of_interaction').distinct()
    context={'records':list()}

    for row in data:
        adat = {"protein": row[1]}
        adat["name"] = row[2]
        adat["organism"] = row[3]
        adat["type_of_interaction"] = row[4]
        expmethod = ProteinInteractor.objects.filter(protein=row[0]).values_list(
            "experimental_method").distinct().order_by("experimental_method")
        adat["experimental_method"] = ', '.join(str(item[0]) for item in expmethod)
        integrins = ProteinInteractor.objects.filter(protein=row[0]).values_list(
            "target_integrin").distinct().order_by("target_integrin")
        adat["integrins"] = ', '.join(str(item[0]) for item in integrins)
        # print(adat)
        context['records'].append(adat)

    return render(request, 'app/help.html', context)

mimic/app/views/home.py
from django.views.generic.detail import DetailView
from django_tables2 import SingleTableView
from django.shortcuts import render
from app.models import Monomer, Dimer, Drug, Pdb, ProteinInteractor
import pandas as pd
import pprint

# List of 'random' example dimers to select from.
RANDOM_EXAMPLE_DIMERS = [
    'alpha-IIb_beta-3',
    'alpha-1_beta-1',
    'alpha-4_beta-1',
    'alpha-4_beta-7',
    'alpha-5_beta-1',
    'alpha-V_beta-3',
    'alpha-V_beta-6',
]

def HomePageView(request):
    """ The home page view.
    """
    dimers = Dimer.objects.all()
    drugs = Drug.objects.all()
    pdbs = Pdb.objects.all()
    protein_interactors = ProteinInteractor.objects.all()

    random_dimer = Dimer.objects.filter(
        lookup_name__in=RANDOM_EXAMPLE_DIMERS,
    ).order_by("?")[0]

    random_dimer_counts = {
        #'interactors': random_dimer.proteininteractor_set.count(),
        'drugs': random_dimer.drug_set.count(),
        'structures': sum([
            random_dimer.alpha.pdb_alpha.count(),
            random_dimer.beta.pdb_beta.count()
        ])
    }

    context = {
        'dimers': dimers,
        'random_dimer': random_dimer,
        'random_dimer_counts': random_dimer_counts,
        'drugs': drugs,
        'pdbs': pdbs,
        'protein_interactors': protein_interactors,
    }

    return render(request, 'app/home.html', context)


mimic/app/views/interactions.py
import re

from app.models import ProteinInteractor, ProteinInformation, Protein
from django.views.generic import TemplateView


class InteractionsView(TemplateView):
    template_name = 'app/interactions.html'

    def get_context_data(self, **kwargs):
        entry_id = kwargs['protein']

        if re.match("\d+", entry_id):
            data = {"entry": Protein.objects.filter(id=entry_id).values().first()}
            data["peptide"] = True
            data["records"] = ProteinInteractor.objects.filter(protein_id=entry_id)

        else:
            data = {"entry": ProteinInteractor.objects.filter(protein__uniprot=entry_id).all().first()}
            data["peptide"] = False
            data["records"] = ProteinInteractor.objects.filter(protein__uniprot=entry_id)

            data["information"] = ProteinInformation.objects.filter(protein__uniprot=entry_id).first()

        return data

mimic/app/templates/app/about.html
{% extends "mimic/base.html" %}

{% block content %}

<div class='row'>
    <div class='col-lg'>
        <h1>About MimicDB</h1>
    </div>
</div>

<div class='row'>
    <div class='col-lg'>
        <p>
            Integrins are heterodimeric receptors crucial for the
            differentiation, migration, adhesion and survival of metazoan
            cells. They mediate cell attachment via interactions with adhesion
            molecules and are also targeted by viper venom disintegrins and
            several viruses as entry points. The importance of integrin
            signaling is evident from integrin-linked diseases, ranging from
            developmental defects through Crohn's disease to tumor formation.
        </p>
        <p>
            Despite their importance, for most of the 24 human integrins
            nothing is known about the molecular details of their interactions.
            This hampers their effective biomedical modulation and the
            successful targeting of integrin-related diseases. The moderate
            success of current targeting efforts have demonstrated the need for
            detailed structural understanding of various binding events. Thus,
            the delineation of the structural principles of known integrin
            interactions and the identification of unknown integrin binding
            modes in molecular detail is essential to understand the complex
            integrin signaling pathway.
        </p>
        <p>
            MimicDB serves as a platform to enable such large-scale systematic
            research efforts by integrating available data on the sequences,
            subunits, structures, and expression patterns of all 24 human
            integrins, together with information about known extracellular
            integrin-binding ligands, and developed drugs that modulate these
            binding events.
        </p>
    </div>
</div>

{% endblock content %}

mimic/app/templates/app/dimer_detail.html
{% extends "mimic/base.html" %}

{% block content %}

<div class='row'>
    <div class='col-lg'>
        <h1>Integrin: <strong>{{ dimer.display_name }}</strong></h1>
    </div>
</div>

<div class='row'>
    <div class='col-md'>
        <div class='card'>
            <div class='card-header'>
                Basic information
            </div>
            <div class='card-body'>
                <ul>
                    <li>

                        <strong>α subunit: </strong>
                        <a href="{% url 'alpha' dimer.alpha.name %}">
                            {{ dimer.alpha.display_name }}
                        </a>
                    </li>
                    <li>
                        <strong>β subunit: </strong>
                        <a href="{% url 'beta' dimer.beta.name %}">
                            {{ dimer.beta.display_name }}
                        </a>
                    </li>
                    <li>
                        <strong>Tissue expression:</strong>
                        {{ dimer.expression }}
                    </li>
                    <li>
                        <strong>Drugs:</strong>
                        {% if dimer.drug_set.all %}
                            {% for drug in dimer.drug_set.all %}
                                <a href="{% url 'drug' drug.name %}">
                                    {{ drug.name }}</a><!--don't insert space
                                -->{% if not forloop.last %},{% endif %}
                            {% endfor %}
                        {% else %}
                            (none)
                        {% endif %}
                    </li>
                    {% if not dimer.proteininteractor_set.all %}
                        <li>
                            <strong>Extracellular ligands: </strong>(none)
                        </li>
                    {% else %}
                        <li>
                            <strong>Extracellular ligands: </strong>
                        </li>
                        <ul>
                            {% for protein_interactor in dimer.proteininteractor_set.all %}
                                <li>
                                    <a href="{% url 'protein-interactor' protein_interactor.protein.uniprot %}">
                                    {{ protein_interactor.name }}</a>
                                    {% if protein_interactor.taxonomic_group == 'Human' %}
                                        <em>native</em>
                                    {% else %}
                                    <em>non-native ({{ protein_interactor.taxonomic_group }})</em>
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class='col-md'>
        <div class='card'>
            <div class='card-header'>
                Structural information
            </div>
            <div class='card-body'>
                {{ dimer.generate_dimer_diagram | safe }}
                <p>
                    The figure shows in color the domains and regions of the
                    α (blue) and β (red) subunits that have structural
                    information in the PDB. Hovering over domains or regions
                    displays the corresponding PDB IDs.
                </p>
            </div>
        </div>
    </div>
</div>
<p>&nbsp;</p>
<div class='row'>
    <div class='col-md'>
        <div class='card'>
            <div class='card-header'>Domain architecture of {{ dimer.alpha.display_name }} (with UniProt numbering)</div>
            <div class='card-body'>
                <ul>
                    {% for m2s in dimer.alpha.monomertostructure_set.all %}
                        <li>{{ m2s.structure.name }} ({{ m2s.start }} - {{ m2s.stop }})</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class='col-md'>
        <div class='card'>
            <div class='card-header'>Domain architecture of {{ dimer.beta.display_name }} (with UniProt numbering)</div>
            <div class='card-body'>
                <ul>
                    {% for m2s in dimer.beta.monomertostructure_set.all %}
                        <li>{{ m2s.structure.name }} ({{ m2s.start }} - {{ m2s.stop }})</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
});
$('[data-toggle="popover"]').popover({ trigger: "manual" , html: true, animation:false})
    .on("mouseenter", function () {
        var _this = this;
        $(this).popover("show");
        $(".popover").on("mouseleave", function () {
            $(_this).popover('hide');
        });
    }).on("mouseleave", function () {
        var _this = this;
        setTimeout(function () {
            if (!$(".popover:hover").length) {
                $(_this).popover("hide");
            }
        }, 300);
});
</script>
{% endblock content %}


mimic/app/templates/app/dimer_list.html
{% extends "mimic/base.html" %}
{% load django_tables2 %}

{% block content %}

<div class='row'>
    <div class='col-lg'>
        <h1>Integrins</h1>
    </div>
</div>
<div class='row'>
    <div class='col-lg'>
        <p>
            The table lists all 24 known human dimeric integrins. Clicking on the
            <strong>Integrin name</strong> displays information about the dimeric
            receptors, clicking on <strong>α subunit</strong> or
            <strong>β subunit</strong> names displays information about
            specific protein components of the receptors.
        </p>
        <p>
            The table is sortable by clicking on column headers.
        </p>
        {% render_table table %}
    </div>
</div>


{% endblock content %}

mimic/app/templates/app/downloads.html
{% extends "mimic/base.html" %}
{% load static %}

{% block content %}

    <div class='row'>
        <div class='col-lg'>
            <h1>Downloads</h1>
        </div>
    </div>

    <div class="container-fluid">
        <div class="well">
            <div class="row p-4 text-justify">
                The current version (1.0) of MimicDB contains {{ records.count }} interactions.
            </div>
            <div class="row p-4 text-justify">
                The full interaction list is available for download in TSV (tab-separated version).

            </div>
            <hr class="mt-2 mb-3"/>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="row text-center align-middle">
                    <div class=" col-sm-4 col-md-3 p-4">
                        <h4 class="titleh4">Full interaction list of MimicDB</h4>
                    </div>
                    <div class=" col-sm-4 col-md-3 p-4">
                        <a href={% static 'downloads/mimicdb_2024.tsv' %} class="btn
                           btn-out btn-rounded btn-light" role="button" download><i
                            class="bi bi-file-earmark-arrow-down"></i> TSV </a>
                    </div>
                    {#                    <div class=" col-sm-4 col-md-3 p-4">#}
                    {#                        <label class="btn btn-light" for="mySubmit2"><i#}
                    {#                                class="bi bi-file-earmark-arrow-down"></i> XML</label>#}
                    {#                        <input id="mySubmit2" type="submit" value="xml" name="download" class="hidden"/>#}
                    {#                    </div>#}
                    {#                    <div class=" col-sm-4 col-md-3 p-4">#}
                    {#                        <label class="btn btn-light" for="mySubmit3"><i#}
                    {#                                class="bi bi-file-earmark-arrow-down"></i> JSON</label>#}
                    {#                        <input id="mySubmit3" type="submit" value="json" name="download" class="hidden"/>#}
                    {#                    </div>#}
                </div>
        </div>
    </div>

{% endblock content %}

mimic/app/templates/app/drug_list.html
{% extends "mimic/base.html" %}
{% load django_tables2 %}

{% block content %}

<div class='row'>
    <div class='col-lg'>
        <h1>Drugs</h1>
    </div>
</div>
<div class='row'>
    <div class='col-lg'>
        <p>
            The table lists all integrin-targeting drugs that are, or have been
            in clinical use.
        </p>
        <p>
            The table is sortable by clicking on column headers.
        </p>
        {% render_table table %}
    </div>
</div>

{% endblock content %}

mimic/app/templates/app/monomer_detail.html
{% extends "mimic/base.html" %}

{% block content %}

<div class='row'>
    <div class='col-lg'>
        <h1>Integrin subunit: <strong>{{ monomer.display_name }}</strong></h1>
    </div>
</div>

<div class='row'>
    <div class='col-md'>
        <div class='card'>
            <div class='card-header'>Basic information</div>
            <div class='card-body'>
                <ul>
                    <li><strong>Subunit name: </strong>{{ monomer.display_name }}</li>
                    <li><strong>Uniprot accession: </strong><a target="_blank" href="{{ monomer.uniprot_link }}">{{ monomer.protein.uniprot }}</a></li>
                    <li><strong>Ensembl gene ID: </strong><a target="_blank" href="{{ monomer.ensembl_link }}">{{ monomer.ensg }}</a></li>
                    <li><strong>Alternative names: </strong>
                        {% if monomer.protein.alternativename_set.all %}
                            {{ monomer.protein.alternativename_set.all|join:", " }}
                        {% else %}
                            (none)
                        {% endif %}
                    </li>
                    <li><strong>Tissue expression: </strong> {{ monomer.expression }}</li>
                    {% if not monomer.alpha_interaction_domain is None %}
                        <li><strong>Inserted interaction domain present: </strong> {{ monomer.alpha_interaction_domain|yesno }}</li>
                    {% endif %}
                    <li><strong>Present in the following dimeric receptors: </strong>
                        <ul>
                            {% for dimer in monomer.alpha.all %} 
                                <li><a href="{% url 'dimer' dimer.lookup_name %}">
                                        {{ dimer.display_name }}
                                    </a></li>
                            {% endfor %}
                            {% for dimer in monomer.beta.all %} 
                                <li><a href="{% url 'dimer' dimer.lookup_name %}">
                                        {{ dimer.display_name }}
                                    </a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class='col-md'>
        <div class='card'>
            <div class='card-header'>Domain architecture of {{ monomer.display_name }} (with UniProt numbering)</div>
            <div class='card-body'> 
                <ul>
                    {% for m2s in monomer.monomertostructure_set.all %}
                        <li>{{ m2s.structure.name }} ({{ m2s.start }} - {{ m2s.stop }})</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
<p>&nbsp;</p>
<div class='row'>
    <div class='col-lg'>
        <div class='card'>
            <div class='card-header'>{{ monomer.display_name }} sequence</div>
            <div class='card-body'> 
                <p>{{ monomer.sequence }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}